### ISSUE TITLE
[v2] - Upgrade heroicons v1 to v2

### ISSUE THREAD

**Issue by ph7jack** [PH7-Jack/livewire-ui#528]
**Todo:**
- [x] Remove the icons folder and use the vendor folder
- [x] Update icons documentation
- [x] Fix breaking changes in the documentation 
- [x] Refactor icon component 
- [x] Refactor icon route
- [x] Update component icons breaking changes

**Dependency**
- [wireui/heroicons](https://github.com/wireui/heroicons)
